# Generator of the Lean section "An infinite family on cycles" in MaximallyEvenEnergy.lean.
# Needs sympy. Run:  python3 gen_family.py   (writes family.lean.txt and prints the differences)
# Generate the Lean code for the infinite family C_{4x}, x = m + 8, A = {0, x-1, 2x, 3x-1}.
import sympy as sp
m = sp.symbols('m', nonnegative=True)
N = (4, 32)
def lin(a, b): return a*m + b
def nat(a, b):
    if a == 0: return f"{b}"
    s = "m" if a == 1 else f"{a} * m"
    return s if b == 0 else f"{s} + {b}"
def rat(a, b):
    if a == 0: return f"({b} : ℚ)"
    s = "(m : ℚ)" if a == 1 else f"{a} * (m : ℚ)"
    return f"({s})" if b == 0 else f"({s} + {b})"
sets = {
 'A':  [(0,0),(1,7),(2,16),(3,23)],
 'M':  [(0,0),(1,8),(2,16),(3,24)],
 'P1': [(0,1),(1,7),(2,16),(3,23)],   # 0 -> 1
 'P2': [(1,7),(2,16),(3,23),(4,31)],  # 0 -> N-1
 'P3': [(0,0),(1,6),(2,16),(3,23)],   # x-1 -> x-2
 'P4': [(0,0),(1,8),(2,16),(3,23)],   # x-1 -> x
 'P5': [(0,0),(1,7),(2,15),(3,23)],   # 2x -> 2x-1
 'P6': [(0,0),(1,7),(2,17),(3,23)],   # 2x -> 2x+1
 'P7': [(0,0),(1,7),(2,16),(3,22)],   # 3x-1 -> 3x-2
 'P8': [(0,0),(1,7),(2,16),(3,24)],   # 3x-1 -> 3x
}
def dists(pts):
    out = []
    for i in range(4):
        for j in range(i+1, 4):
            da, db = pts[j][0]-pts[i][0], pts[j][1]-pts[i][1]
            ea, eb = N[0]-da, N[1]-db
            # min(delta, N - delta) for all m >= 0
            if ea-da >= 0 and eb-db >= 0: out.append((da, db))
            elif ea-da <= 0 and eb-db <= 0: out.append((ea, eb))
            else: raise ValueError((pts, i, j))
    return out
def energy(pts): return sum(1/lin(*r) for r in dists(pts))
L = []
L.append("/-! ## An infinite family on cycles: `C_{4x}`, `A = {0, x-1, 2x, 3x-1}`, `x = m + 8 ≥ 8`")
L.append("")
L.append("The Lean code of this section was generated by `gen_family.py` (same folder). -/")
L.append("")
for name, pts in sets.items():
    elems = ", ".join(f"⟨{nat(*p)}, by omega⟩" for p in pts)
    L.append(f"/-- The set `{{{', '.join(nat(*p) for p in pts)}}}` in `C_{{4(m+8)}}`. -/")
    L.append(f"def fam{name} (m : ℕ) : Finset (Fin (4 * (m + 8))) := {{{elems}}}")
    L.append("")
    rs = dists(pts)
    rhs = " + ".join(f"1 / {rat(*r)}" for r in rs)
    named = " ".join(f"(r{k+1} := {nat(*r)})" for k, r in enumerate(rs))
    L.append(f"theorem energy_fam{name} (m : ℕ) : energy inv cycleDist (fam{name} m) =")
    L.append(f"    {rhs} := by")
    L.append(f"  unfold fam{name}")
    L.append(f"  refine (energy_four_val inv cycleDist ?_ ?_ ?_ {named} ?_ ?_ ?_ ?_ ?_ ?_).trans ?_")
    L.append(f"  all_goals first")
    L.append(f"    | exact Fin.mk_lt_mk.2 (by omega)")
    L.append(f"    | (simp only [cycleDist, pathDist]; omega)")
    L.append(f"    | (simp only [inv]; push_cast; ring)")
    L.append("")
EA = energy(sets['A'])
def lt_lemma(nm, lo, hi, doc):
    diff = sp.factor(sp.together(energy(sets[hi]) - energy(sets[lo])))
    num, den = sp.fraction(diff)
    pn = sp.Poly(sp.expand(num), m); pd = sp.Poly(sp.expand(den), m)
    assert all(c > 0 for c in pn.coeffs()), (nm, pn)
    assert all(c > 0 for c in pd.coeffs()), (nm, pd)
    def poly_q(p):
        terms = []
        for (k,), c in sorted(p.terms(), reverse=True):
            if k == 0: terms.append(f"{c}")
            elif k == 1: terms.append(f"{c} * (m : ℚ)")
            else: terms.append(f"{c} * (m : ℚ) ^ {k}")
        return "(" + " + ".join(terms) + ")"
    rhs_lo = " + ".join(f"1 / {rat(*r)}" for r in dists(sets[lo]))
    rhs_hi = " + ".join(f"1 / {rat(*r)}" for r in dists(sets[hi]))
    L.append(f"/-- {doc} -/")
    L.append(f"theorem {nm} (m : ℕ) : energy inv cycleDist (fam{lo} m) < energy inv cycleDist (fam{hi} m) := by")
    L.append(f"  rw [energy_fam{lo}, energy_fam{hi}, ← sub_pos]")
    L.append(f"  have key : ({rhs_hi}) - ({rhs_lo}) =")
    L.append(f"      {poly_q(pn)} / {poly_q(pd)} := by")
    L.append(f"    field_simp")
    L.append(f"    ring")
    L.append(f"  rw [key]")
    L.append(f"  positivity")
    L.append("")
    return diff
print("-- differences:")
for k in range(1, 9):
    d = lt_lemma(f"famA_lt_famP{k}", 'A', f'P{k}', f"Perturbation {k} of `famA` has larger energy.")
    print(k, d)
d = lt_lemma("famM_lt_famA", 'M', 'A', "The maximally even set has smaller energy than `famA`.")
print('M', d)
open('family.lean.txt', 'w').write("\n".join(L) + "\n")
